version: '3.8'
services:
  mongodb:
    image: mongo:4.4.0
    container_name: jfrapp-mongo-database
    ports:
      - '27017:27017'
    expose:
      - '27017'
    volumes:
      - mongodata:/data/db
  nginx:
    build: ./development
    container_name: jfrapp-development-nginx
    depends_on:
      - back-end-api
      - front-end
    ports:
      - '80:80'
    volumes:
      - type: bind
        source: ./front-end
        target: /app
    working_dir: /app
  front-end:
    image: node:14.8.0-stretch
    container_name: jfrapp-development-web
    # For advanced environment variables, go to url https://create-react-app.dev/docs/advanced-configuration/.
    command: sh -c 'yarn start'
    depends_on:
      - back-end-api
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: ./front-end
        target: /app
    working_dir: /app
    stdin_open: true
  back-end-api:
    image: node:14.8.0-stretch
    container_name: jfrapp-development-api
    command: sh -c 'node --inspect=0.0.0.0:9229 index.js'
    environment:
      LISTEN_ON: 0.0.0.0
      PORT: 8080
      MONGO_CONNECTION_STRING: mongodb+srv://application-user:wA2GVyvIaCd5bWV1@local-development-clust.rtjbr.azure.mongodb.net/javascript-framework-ratings?retryWrites=true&w=majority
    depends_on:
      - mongodb
    ports:
      - '9229:9229'
      - '8080:8080'
    volumes:
      - type: bind
        source: ./back-end-api
        target: /app
    working_dir: /app
volumes:
  mongodata:
