apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end-api
  labels:
    name: back-end-api
    app-type: api
spec:
  replicas: 3
  strategy:
    type: ~ # Will use the default RollingUpdate.
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 25%
  selector:
    matchLabels:
      name: back-end-api
  template:
    metadata:
      labels:
        name: back-end-api
    spec:
      containers:
        - name: back-end-api
          image: [acrUrl]/back-end-api:[build-id]
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: MONGO_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: mongodbo-connection-string-secret
                  key: MONGO_CONNECTION_STRING
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: back-end-api-configmap
                  key: PORT
            - name: LISTEN_ON
              valueFrom:
                configMapKeyRef:
                  name: back-end-api-configmap
                  key: LISTEN_ON
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            httpGet:
              path: /api/probetest
              port: 8080
              scheme: HTTP
