apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-app-deployment
  labels:
    name: front-end-app
    app-type: web
spec:
  replicas: 3
  strategy:
    type: ~ # Will use the default RollingUpdate.
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 25%
  selector:
    matchLabels:
      name: front-end-app
  template:
    metadata:
      labels:
        name: front-end-app
    spec:
      containers:
        - name: front-end-app
          image: [acrUrl]/front-end-app:[build-id]
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
