apiVersion: v1
kind: Service
metadata:
  name: back-end-api-svc
  namespace: staging
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    name: back-end-api
